#if !canImport(ObjectiveC)
import XCTest

extension AppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppTests = [
        ("testHelloWorld", testHelloWorld),
    ]
}

extension ProductTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProductTests = [
        ("testGetAllProduct", testGetAllProduct),
        ("testGetProductById", testGetProductById),
    ]
}

extension UserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserTests = [
        ("testChangeUserData", testChangeUserData),
        ("testLogin", testLogin),
        ("testLogout", testLogout),
        ("testRegistration", testRegistration),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AppTests.__allTests__AppTests),
        testCase(ProductTests.__allTests__ProductTests),
        testCase(UserTests.__allTests__UserTests),
    ]
}
#endif
